### ISSUE TITLE
배경을 클릭했을 때 view를 dismiss하고 싶다면

### ISSUE THREAD

**Issue by Taehyeon-Kim** [Taehyeon-Kim/TIL#21]
### 문제 상황

다음과 같은 상황이 있다라고 했을 때, 우리는 컨텐츠가 들어있는 부분 말고
백그라운드를 클릭했을 때 뷰를 해제하거나 dismiss 하고 싶다.

어떻게 해야할까?

<img src = "https://user-images.githubusercontent.com/61109660/166957585-92bdfbbc-cfab-4099-abbc-a868ae4ba5cb.png" width = "300" />

### 내가 이전에 쓰던 코드
```swift
override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
    dismiss(animated: true)
}
```
> 그 동안 이렇게 사용해왔다.
> 근데 이렇게 코드를 작성했을 때 한 가지 문제점이 있다.
> 컨텐츠가 들어있는 뷰(띄워진 뷰, 여기서는 팝업)을 클릭해도 view가 dismiss된다.

### 지금에서야 쓰는 코드
```swift
override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
    super.touchesBegan(touches, with: event)
  
    if let touch = touches.first,
       touch.view == self.view {
        dismiss(animated: true)
    }    
}
```
이벤트에 들어온 UITouch 객체를 print 해보면
다음과 같이 touch객체의 정보를 확인할 수가 있는데

<img width="679" alt="스크린샷 2022-05-06 오전 1 13 12" src="https://user-images.githubusercontent.com/61109660/166967199-2f8c78d4-a01d-47e3-8a38-4f7d862768db.png">

내가 지금 tap한 횟수가 몇 번인지, 내가 touch한 view의 정보는 무엇인지 등 정말 다양한 정보를 알 수 있다.  
위에서 작성한 코드를 해석해보면 touch 객체의 정보 중에서 지금 touch 이벤트가 일어난 view가 배경 view와 같은지를 확인하고  
같다면 dismiss를 해주는 분기 처리를 하고 있는 것을 확인할 수 있다.

### 마무리하며
배경 클릭했을 때, 키보드를 해제(hide)하는 부분에서 사용이 가능하지 않을까 싶다.

**Comment by seungchan2** [comment]
지린다 . .

**Comment by EunHee-Jeong** [comment]
진정한 LGTM
